vich_uploader:
    # Specifies the database driver used for persistence
    db_driver: orm  # Using Doctrine ORM for persistence

    metadata:
        # Defines how metadata is loaded; using PHP attributes (recommended for Symfony 6+)
        type: attribute  

    mappings:
        ads:
            # Base URL prefix for uploaded files
            uri_prefix: /images/products  
            
            # Path where files will be stored
            upload_destination: '%kernel.project_dir%/public/images/products'  

            # Generates a unique file name automatically
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  

            # Whether to inject the file into the entity when loading it from the database
            inject_on_load: false  

            # If true, deletes the previous file when updating the entity with a new one
            delete_on_update: true  

            # If true, deletes the file when the entity is removed from the database
            delete_on_remove: true  