controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\User\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\User\SecurityController::logout
    methods: [GET, POST]

app_register:
    path: /register
    controller: App\Controller\User\RegistrationController::register
    methods: [GET, POST]

app_verify_email:
    path: /verify/email
    controller: App\Controller\User\RegistrationController::verifyUserEmail
    methods: [GET]

app_verify_code:
    path: /verify/code
    controller: App\Controller\User\RegistrationController::verifyCode
    methods: [GET, POST]

app_create_ad:
    path: /create
    controller: App\Controller\IndexController::createAd
    methods: [GET, POST]

app_update_ad:
    path: /my-announces/update/{id}
    controller: App\Controller\Ad\UpdateController::update
    methods: [GET, POST]

app_delete:
    path: /delete/{id}
    controller: App\Controller\Ad\DeleteController::delete
    methods: [GET, POST]

app_profile:
    path: /profile
    controller: App\Controller\User\ProfileController::index
    methods: [GET, POST]

app_categories:
    path: /category/{id}
    controller: App\Controller\Category\IndexController::productsByCategory
    methods: [GET, POST]

ad_search:
    path: /search
    controller: App\Controller\Ad\AdController::search
    methods: [GET]

app_update_profile:
    path: /profile/update
    controller: App\Controller\User\ProfileController::updateProfile
    methods: [GET, POST]